// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd8oGzc_u_u2rqzXQbFmvwCJHUkP1HsUQ',
    appId: '1:478391183627:web:e7a8c363053b2c5f73da0e',
    messagingSenderId: '478391183627',
    projectId: 'campus-connect-5ef22',
    authDomain: 'campus-connect-5ef22.firebaseapp.com',
    storageBucket: 'campus-connect-5ef22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXe2BXL9wXp2CRWzmMlOVB6H4LHuPr3bU',
    appId: '1:478391183627:android:811e61a03ee1da2273da0e',
    messagingSenderId: '478391183627',
    projectId: 'campus-connect-5ef22',
    storageBucket: 'campus-connect-5ef22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1SHNMLVO9hk_FhsS2IMD-BWXW8_E4HBw',
    appId: '1:478391183627:ios:c2e99faf64c1a11873da0e',
    messagingSenderId: '478391183627',
    projectId: 'campus-connect-5ef22',
    storageBucket: 'campus-connect-5ef22.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1SHNMLVO9hk_FhsS2IMD-BWXW8_E4HBw',
    appId: '1:478391183627:ios:c2e99faf64c1a11873da0e',
    messagingSenderId: '478391183627',
    projectId: 'campus-connect-5ef22',
    storageBucket: 'campus-connect-5ef22.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd8oGzc_u_u2rqzXQbFmvwCJHUkP1HsUQ',
    appId: '1:478391183627:web:941856e1c72d969073da0e',
    messagingSenderId: '478391183627',
    projectId: 'campus-connect-5ef22',
    authDomain: 'campus-connect-5ef22.firebaseapp.com',
    storageBucket: 'campus-connect-5ef22.firebasestorage.app',
  );
}
